package com.PersonalProject.Jemo.exception;

public enum ErrorCodes {

    CATEGORY_NOT_FOUND(1000),
    CATEGORY_NOT_VALID(1001),
    CATEGORY_ALREADY_IN_USE(1002),





    ORDER_CUSTOMER_NOT_FOUND(3000),
    ORDER_CUSTOMER_NOT_VALID(3001),
    ORDER_CUSTOMER_NON_MODIFIABLE(3002),
    ORDER_CUSTOMER_ALREADY_IN_USE(3003),





    PRODUCT_NOT_FOUND(5000),
    PRODUCT_NOT_VALID(5001),
    PRODUCT_ALREADY_IN_USE(5002),






    USER_NOT_FOUND(7000),
    USER_NOT_VALID(7001),
    USER_ALREADY_EXISTS(7002),
    USER_CHANGE_PASSWORD_OBJECT_NOT_VALID(7003),



    MVT_STK_NOT_FOUND(8000),
    MVT_STK_NOT_VALID(8001),


    ITEM_ORDER_CUSTOMER_NOT_FOUND(9000),



    BAD_CREDENTIALS(11000),


    UPDATE_PHOTO_EXCEPTION(12000),
    UNKNOWN_CONTEXT(12001),

    CUSTOMER_ALREADY_EXISTS(12002),
    CUSTOMER_CHANGE_PASSWORD_OBJECT_NOT_VALID(12003),

    CART_NOT_FOUND(12004),
    CART_NOT_VALID(12005),


    ;
    private final int Codes;

    ErrorCodes(int codes){

        this.Codes=codes;
    }

    public int getErrorCodes(){
        return Codes;
    }

}
