package com.PersonalProject.Jemo.exception;

public enum ErrorCodes {

    CATEGORY_NOT_FOUND(1000),
    CATEGORY_NOT_VALID(1001),
    CATEGORY_ALREADY_IN_USE(1002),


    CUSTOMER_NOT_FOUND(2000),
    CUSTOMER_NOT_VALID(2001),
    CUSTOMER_ALREADY_IN_USE(2002),


    ORDER_CUSTOMER_NOT_FOUND(3000),
    ORDER_CUSTOMER_NOT_VALID(3001),
    ORDER_CUSTOMER_NON_MODIFIABLE(3002),
    ORDER_CUSTOMER_ALREADY_IN_USE(3003),


    ORDER_SUPPLIER_NOT_FOUND(4000),
    ORDER_SUPPLIER_NOT_VALID(4001),
    ORDER_SUPPLIER_NON_MODIFIABLE(4002),
    ORDER_SUPPLIER_ALREADY_IN_USE(4003),


    PRODUCT_NOT_FOUND(5000),
    PRODUCT_NOT_VALID(5001),
    PRODUCT_ALREADY_IN_USE(5002),



    SUPPLIER_NOT_FOUND(6000),
    SUPPLIER_NOT_VALID(6001),
    SUPPLIER_ALREADY_IN_USE(6002),


    USER_NOT_FOUND(7000),
    USER_NOT_VALID(7001),
    USER_ALREADY_EXISTS(7002),
    USER_CHANGE_PASSWORD_OBJECT_NOT_VALID(7003),



    MVT_STK_NOT_FOUND(8000),
    MVT_STK_NOT_VALID(8001),


    ITEM_ORDER_CUSTOMER_NOT_FOUND(9000),
    ITEM_ORDER_SUPPLIER_NOT_FOUND(10000),


    BAD_CREDENTIALS(11000),


    UPDATE_PHOTO_EXCEPTION(12000),
    UNKNOWN_CONTEXT(12001),

    CUSTOMER_ALREADY_EXISTS(12002),
    CUSTOMER_CHANGE_PASSWORD_OBJECT_NOT_VALID(12003)

    ;
    private final int Codes;

    ErrorCodes(int codes){

        this.Codes=codes;
    }

    public int getErrorCodes(){
        return Codes;
    }

}
